[package]
name = "LeetCode"
version = "0.5.0"
authors = ["mbuyankin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
